application: mobile-diarios
version: 1-6-19
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /html/(.*)
  static_files: static/html/\1
  upload: static/html/(.*)

- url: /apps/eldia/(.*\.(jad))
  static_files: static/apps/eldia/\1
  upload: /static/apps/eldia/(.*\.(jad))
  mime_type: text/vnd.sun.j2me.app-descriptor
   
- url: /apps/eldia/(.*\.(cod))
  static_files: static/apps/eldia/\1
  upload: /static/apps/eldia/(.*\.(cod))
  mime_type: application/vnd.rim.cod
  
- url: /googlebf512d3ebbc1cfaf\.html
  static_files: static/googlebf512d3ebbc1cfaf.html
  upload: static/googlebf512d3ebbc1cfaf.html
  
- url: /(css|img|js|mvp_1)/(.*)
  static_files: static/\1/\2
  upload: static/(.*)

- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)
  
- url: /static
  static_dir: static
  expiration: 1d

- url: /shell
  login: admin
  script: shell.app

- url: /shell.do
  login: admin
  script: shell.app

- url: /_ah/queue/deferred
  script: main.app
  login: admin
 
- url: .*
  script: main.app

  
  
libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

- name: lxml
  version: "2.3"
